#!/usr/bin/env bash

# Check if correct number of parameters is passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer file using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$server_ip":~/ 

# Check if scp command executed successfully
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Error: File transfer failed"
fi
