#!/usr/bin/env bash
#Transfers a file to a server

if [ $# -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

# Assign parameters to variables. We can use the following in the code below without using double quotes.
#PATH_TO_FILE="$1"
#IP="$2"
#USERNAME="$3"
#PATH_TO_SSH_KEY="$4"

if [ $# -ge 4 ];
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;    
