#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
#to another page
#a “301 Moved Permanently”


# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure Nginx to listen on port 80
#sudo ufw allow 'Nginx HTTP'

# Start Nginx
#sudo service nginx start

# Create a file with "Hello World!" message
#sudo echo "Hello World!" > /var/www/html/index.html
#SC2024: sudo doesn't affect redirects. Use ..| sudo tee file
echo "Hello World!" | sudo tee /var/www/html/index.html

#Configure your Nginx server so that /redirect_me is redirecting
#to another page
#a “301 Moved Permanently”
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/itssamaribrahim permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
