#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

#Updates the package lists for upgrades for packages that need upgrading
sudo apt-get update

#Installs the Nginx web server. The -y flag automatically answers yes to any prompts
sudo apt-get install -y nginx

#Creates a directory named html inside the /etc/nginx directory. This directory will hold HTML files served by Nginx
sudo mkdir /etc/nginx/html

#Creates an empty file named index.html inside the /etc/nginx/html directory
sudo touch /etc/nginx/html/index.html

#Writes the text "Hello World!" into the index.html file
echo "Hello World!" > /etc/nginx/html/index.html

#Creates an empty file named 404.html inside the /etc/nginx/html directory
sudo touch /etc/nginx/html/404.html

#Writes the text "Ceci n'est pas une page" into the 404.html file
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

#the Nginx server configuration to be printed into the default configuration file for Nginx (/etc/nginx/sites-available/default)

#Nginx Configuration:

#       The provided Nginx configuration sets up a server block listening on port 80 with a custom header X-Served-By set to the hostname of the server.
#       It specifies the root directory where HTML files are located (/etc/nginx/html) and the default index files (index.html and index.htm).
#       It defines a location block /redirect_me, which redirects to a specific URL using a 301 HTTP status code.
#       It configures a custom error page for 404 errors to serve the 404.html file located in the /etc/nginx/html directory
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

#Restarts the Nginx service to apply the changes made to the configuration
sudo service nginx restart
