#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create a file with "Hello World!" message
#sudo echo "Hello World!" > /var/www/html/index.html
#SC2024: sudo doesn't affect redirects. Use ..| sudo tee file
echo "Hello World!" | sudo tee /var/www/html/index.html

#Configure your Nginx server so that /redirect_me is redirecting
#to another page
#a “301 Moved Permanently”
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/itssamaribrahim permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Create a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create an HTTP response header
sudo sed -i "/server_name _/s/$/\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t
# Restart Nginx
sudo service nginx restart
