#!/usr/bin/env bash
# Sets nginx for listening to 80 port
sed -i 's/listen 8080 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
