#!/usr/bin/env bash
# Using awk to group visitors by IP and HTTP status code, and then display the data ordered by occurrence number

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
